
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fintrack-ui-ingress
  namespace: fintrack
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    certmanager.k8s.io/issuer: "letsencrypt-cluster-issuer"
    certmanager.k8s.io/acme-challenge-type: http01
spec:
  tls:
  - hosts:
    - fintrack-ui.kbaenak.tech
    secretName: tls-cert
  rules:
  - host: fintrack-ui.kbaenak.tech
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: fintrack-ui-service
            port:
              number: 1080

